//startsWith(); 
//endsWith();
//indexOf();
//lastIndexOf();
//padStart();
//padEnd()
//repeat();
//split();
//substring();
//toLowerCase();
//toUppercase();
//toString();
//trim();
//trimStart()
//trimEnd();
let cadena = "hola";
let cadena2 = "isaac";
let resultado = cadena.concat(" " + cadena2);
document.write(resultado + "<br>");
let cadena3 = "hola isaac tambien";
let cadena4 = "hola ";
//startsWith() me indica si una determinada cadena inicia con los caracteres que le pase
let resultado2 = cadena3.startsWith(cadena4);
let cadena5 = "hola isaac tambien";
let cadena6 = "ambien";
//endsWith() me indica si una determinada cadena inicia con los caracteres que le pase
let resultado3 = cadena5.endsWith(cadena6);
let cadena7 = "hola isaac tambien nota";
//includes() se le pasa una cadena y devuele como resultado si esta cadena se encuenta en el string que se esta buscando
let resultado4 = cadena7.includes("cristal");
let cadena8 = "Cristal is very very smart";
let resultado5 = cadena8.indexOf("smart");
let cadena9 = "Cristal is very very smart smart smart";
let resultado6 = cadena9.lastIndexOf("smart");
let cadena10 = "Cristal";
let resultado7 = cadena10.padStart(10, "12");
let cadena11 = "Cristal";
let resultado8 = cadena11.padEnd(10, "12");
let cadena12 = "Cristal ";
let resultado9 = cadena12.repeat(2);
let cadena13 = "Cristal como estas";
let resultado10 = cadena13.split("como");
let cadena14 = "Cristal como estas";
let resultado11 = cadena14.substring(0,2);
let cadena15 = "CRISTAL COMO ESTAS";
let resultado12 = cadena15.toLowerCase();
let cadena16 = "cristal como estas";
let resultado13 = cadena16.toUpperCase();
let cadena17 = 45;
let resultado14 = cadena17.toString(); 
let cadena18 = " isaac ";
let resultado15 = cadena18.trim();
let cadena19 = "    isac    ";
let resultado16 = cadena19.trimStart();
let cadena20 = "    isac    ";
let resultado17 = cadena19.trimEnd();
document.write(resultado2 + "<br>");
document.write(resultado3 + '<br>');
document.write(resultado4 + `<br>`);
document.write(resultado5 + `<br>`);
document.write(resultado6 + `<br>`);
document.write(resultado7 + `<br>`);
document.write(resultado8 + `<br>`);
document.write(resultado9 + `<br>`);
document.write(resultado10 + `<br>`);
document.write(resultado11 + `<br>`);
document.write(resultado12 + `<br>`);
document.write(resultado13 + `<br>`);
document.write(resultado14 +  2 + "<br>");
document.write(resultado15.length + "<br>");
document.write(resultado16.length + "<br>");
document.write(resultado17.length + "<br>");
